[project]
name = "mglyph-ml"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "ipywidgets>=8.1.7",
    "mglyph>=0.5.5",
    "notebook>=7.4.7",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
]